### ISSUE TITLE
Alpha/Beta release, if possible 

### ISSUE THREAD

**Issue by ZeroHackz** [mayuelala/FollowYourClick#2]
OwO~ Senpai, could we pwease get a super adorable Alpha/Beta release, so the community can join in and help tidy up the code and add optimizers via GitHub pull requests?

I simply adore the project paper, and I'm beyond excited to lend a hand in making it even more fabulous! Since 14 days feels like an eternity in Machine Learning news, let's hurry and make some cute improvements together🥇 ! 🌟 Isn't that just the most precious thing ever? 

_don't torture us:_
![a98](https://github.com/mayuelala/FollowYourClick/assets/15729496/6790f70d-d55e-4f1f-82fc-90d51412ec55)

**Comment by ZeroHackz** [comment]
> 😄 So what should I do ？

UwU~~ Senpai, we have so many options to chooose fwom!  What if we sprinkle some fairy dust and open a magical branch 'beta'? Then all our friends can join that timeline fun and add updates via pull requests! It'll be like a whimsical tea party in code land~☕! Alternatively, how about we unveil a darling v0.1 version as a pre-alpha? It'll feel like unwrapping a precious gift filled with endless possibilities🎁!

What do you prefer, cutie ♥? Let's embark on this journey a bit earlier 💖

**Comment by youcanyoubing** [comment]
> OwO~ Senpai，我们能不能得到一个超级可爱的 Alpha/Beta 版本，这样社区就可以加入进来，帮助整理代码并通过 GitHub 拉取请求添加优化器？
> 
> 我只是喜欢这个项目文件，我非常兴奋能伸出援手，让它变得更加精彩！由于 14 天在机器学习新闻中感觉像是永恒的，让我们一起🥇快点做一些可爱的改进吧！🌟 这难道不是有史以来最珍贵的东西吗？
> 
> _不要折磨我们：_ ![a98](https://private-user-images.githubusercontent.com/15729496/312861875-6790f70d-d55e-4f1f-82fc-90d51412ec55.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2MTAyMjEsIm5iZiI6MTcxMDYwOTkyMSwicGF0aCI6Ii8xNTcyOTQ5Ni8zMTI4NjE4NzUtNjc5MGY3MGQtZDU1ZS00ZjFmLTgyZmMtOTBkNTE0MTJlYzU1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE2VDE3MjUyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczZTU1NjAyYjYxODdkYTZkMjFkYmFkMjcwM2E2NmVmNWZmZWY4NTEyMzE0ZWEwNzc0ZjE4NzQxMjE5NzY5OTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PWG6834K-9jZ8Sr_PruMYOJEOE3K0UJ8tZOyJDBVTqA) [ ](https://private-user-images.githubusercontent.com/15729496/312861875-6790f70d-d55e-4f1f-82fc-90d51412ec55.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2MTAyMjEsIm5iZiI6MTcxMDYwOTkyMSwicGF0aCI6Ii8xNTcyOTQ5Ni8zMTI4NjE4NzUtNjc5MGY3MGQtZDU1ZS00ZjFmLTgyZmMtOTBkNTE0MTJlYzU1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE2VDE3MjUyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczZTU1NjAyYjYxODdkYTZkMjFkYmFkMjcwM2E2NmVmNWZmZWY4NTEyMzE0ZWEwNzc0ZjE4NzQxMjE5NzY5OTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PWG6834K-9jZ8Sr_PruMYOJEOE3K0UJ8tZOyJDBVTqA) ![a98](https://private-user-images.githubusercontent.com/15729496/312861875-6790f70d-d55e-4f1f-82fc-90d51412ec55.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2MTAyMjEsIm5iZiI6MTcxMDYwOTkyMSwicGF0aCI6Ii8xNTcyOTQ5Ni8zMTI4NjE4NzUtNjc5MGY3MGQtZDU1ZS00ZjFmLTgyZmMtOTBkNTE0MTJlYzU1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE2VDE3MjUyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczZTU1NjAyYjYxODdkYTZkMjFkYmFkMjcwM2E2NmVmNWZmZWY4NTEyMzE0ZWEwNzc0ZjE4NzQxMjE5NzY5OTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PWG6834K-9jZ8Sr_PruMYOJEOE3K0UJ8tZOyJDBVTqA) [ ](https://private-user-images.githubusercontent.com/15729496/312861875-6790f70d-d55e-4f1f-82fc-90d51412ec55.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2MTAyMjEsIm5iZiI6MTcxMDYwOTkyMSwicGF0aCI6Ii8xNTcyOTQ5Ni8zMTI4NjE4NzUtNjc5MGY3MGQtZDU1ZS00ZjFmLTgyZmMtOTBkNTE0MTJlYzU1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE2VDE3MjUyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczZTU1NjAyYjYxODdkYTZkMjFkYmFkMjcwM2E2NmVmNWZmZWY4NTEyMzE0ZWEwNzc0ZjE4NzQxMjE5NzY5OTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PWG6834K-9jZ8Sr_PruMYOJEOE3K0UJ8tZOyJDBVTqA)

你这个图可老经典了
