### ISSUE TITLE
How much VRAM does inference consume?

### ISSUE THREAD

**Issue by yumianhuli1** [mayuelala/FollowYourClick#3]
RT，thanks！

**Comment by FlowDownTheRiver** [comment]
is it possible to optimize the code or lower the requirements for lower end gpus? So that 11 gb cards or 8 gb cards can produce results in exchange of time. If there is a way,please implementation will be very nice. 

The project looks very cool.Thanks for the research and hard work.

**Comment by yumianhuli1** [comment]
> Thanks for your attention， you just need a 3090Ti or V100. That is enough!

条件有点不允许。。
